version: '3.8'

services:
  db:
    image: mysql
    container_name: bookings
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: bookingsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - 3307:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    